### ISSUE TITLE
Number of entries

### ISSUE THREAD

**Issue by milkyjaye** [justnorris/easy-photography-portfolio#1]
I love this plugin, it's fantastic! I was wondering if there was a way to add more than 10 entries–every entry I add over 10 does not appear. Thanks!

**Comment by justnorris** [comment]
You can adjust the WordPress settings for a quick fix. The plugin is going to respect the default WordPress `posts_per_page` setting. If you set that you want 20 blog posts per page,  you'll also have 20 portfolio posts per page.

I probably should add a separate setting though. Thanks for letting me know.

**Comment by milkyjaye** [comment]
Oh man well I'm an idiot... I apologize, I'm new to WP and the relationship between pages and plugins. Thanks a lot your plugin is exactly what I needed for my site!

**Comment by justnorris** [comment]
I decided to set the default limit to 100 posts, so starting version `1.0.7` this will probably no longer be an issue. If more than 100 portfolio posts are required - that's about the point where custom theme development should come in along with the plugin, or the pages would take ages to load. This might be even true for 30-40 posts, but for now I'm just going to keep the limit at 100.
