### ISSUE TITLE
I can't retrieve a post from WP_Query

### ISSUE THREAD

**Issue by antpiantadosi** [justnorris/easy-photography-portfolio#2]
I can't retrieve a post from WP_Query with custom field or category... How Can I retrieve a portfolio item with query? Or there aren't shorcodes that I can use to make that?
Thanks

**Comment by justnorris** [comment]
Hey there,
Can you explain in a little more detail what exactly are you trying to do ? 

If you want to query posts, you need to query for `phort_post`, that's the post type of Easy Photography Portfolio posts.

**Comment by antpiantadosi** [comment]
ok I will try!
Thanks and congratulation for plugin!

**Comment by antpiantadosi** [comment]
Thanks. Everything ok!
