### ISSUE TITLE
Can't reach the gallery

### ISSUE THREAD

**Issue by fertigkind** [justnorris/easy-photography-portfolio#4]
Hey there,
My problem is the following: 
The category sites do show the overview of galleries like they should and when I want to click on one of them I can't reach it but get linked back to the main page of my site instead.
Do you have any Idea where that comes from and how to fix it? 

Greetings

**Comment by justnorris** [comment]
Hi there,
For support, you should be using the WordPress.org forums - https://wordpress.org/support/plugin/photography-portfolio

Without seeing your site configuration I can't really tell why you're seeing the issue you have. My guess is that you have multiple portfolio plugins active and they're colliding with Easy Photography Portfolio plugin. If that's the case - deactivate all other portfolio plugins.

**Comment by fertigkind** [comment]
Thanks, @justnorris but no, that is not the case. It might be an other Plugin though.... I will check that.

**Comment by justnorris** [comment]
Let me know what you find out :)

**Comment by fertigkind** [comment]
It was not a problem with other plugins. I deactivated and re-activated the plugin and now it works completely fine.  Who knows what that was. :D

**Comment by justnorris** [comment]
In that case, it was probably the permalink cache. The same effect can also be done by resetting permalinks: https://help.colormelon.com/knowledgebase/reset-permalinks/
