### ISSUE TITLE
new portofolio layout

### ISSUE THREAD

**Issue by kernel52** [justnorris/easy-photography-portfolio#7]
Hi, 

I was just wondering where the new declaration should be done, if this is to be done on a theme.  

I was trying to add the code in functions.php of my theme, but the namespace declaration returns a wsod. 

Could you please advise me on how to proceed? 

thanks

**Comment by justnorris** [comment]
Hey there,
Have you had a chance to look at the wiki? https://github.com/justnorris/easy-photography-portfolio/wiki

Can you show me the code you're using to register a new layout? I could probably more help then :)

**Comment by kernel52** [comment]
Hi Norris and thanks for the quick reply.

Actually I just copied and pasted the bits and pieces from your wiki to functions.php of my custom template (child template). I had of course a look at the wiki, I did my study before posting a request ;) 

Thanks for your help,
Nikolas

```
/**
 * Try to create a new Photogallery template
 */
 
namespace Grid;

use Photography_Portfolio\Frontend\Layout\Single\Single_Portfolio_Layout;

class Grid_Layout_Single extends Single_Portfolio_Layout {

	public $attached_sizes = [

		'thumb' => 'large',
		'full'  => 'full',

	];

	public $appended_classes = [
		'PP_Gallery'       => 'PP_Grid',
		'PP_Gallery__item' => 'PP_Grid__item',
	];


}

add_action(
	'phort/core/register_layouts',

	/**
	 * @var \Photography_Portfolio\Frontend\Layout_Registry $registry
	 */
	function ( $registry ) {

		/**
		 * Single Horizontal Portfolio
		 */
		$registry->add(
		// Fully Qualified class name.
		// You must make sure that your class is included when neccessary, either by autoloading or manually including it
			'grid\Grid_Layout_Single',

			// The layout group. `single` or `archive`
			'single',

			// Your unique layout slug.
			'grid',

			// The title that's going to appear in Portfolio Settings
			esc_html__( 'Grid', 'grid ' )

		);
	});
	

add_filter( 'phort/archive/masonry/attached_sizes', 'theme_prefix_adjust_phort_masonry_sizes' );
add_filter( 'phort/single/masonry/attached_sizes', 'theme_prefix_adjust_phort_masonry_sizes' );

// Alter image size for "Easy Photography Portfolio" masonry layouts
function theme_prefix_adjust_phort_masonry_sizes( $attached_sizes ) {

	if ( $attached_sizes['thumb'] == 'large' ) {
		$attached_sizes['thumb'] = 'thumbnail_masonry';
	}

	return $attached_sizes;
}	


```

**Comment by justnorris** [comment]
Hi Nikolas,
The problem is probably that you're namespacing your functions.php file - it's best that you use separate files for classes, then import that class, and then register the layout.

Also, I should probably make the development interface a lot easier to use. I have some ideas, but I haven't been able to do it yet.

Also, I noticed that your FQN is `grid\Grid_Layout_Single`, but your namespace is `Grid` - so that's probably the reason it's not working.

And finally - when writing any code - always, always, always enable WP_DEBUG and PHP Errors and Notices. You should be seeing a PHP error, not a WSOD.

I hope that helps!

**Comment by kernel52** [comment]
I thought of separating the files, but went for the lazy approach :) 

I am still fiddling around with WP so I am not always sure on how to proceed. PHP-wise, it makes sense that you need separate files for classes. I'll proceed as you advise me and I'll keep you posted.

Your framework is quite impressive, I must say. But the wiki part, is a good start to begin exploring and I'll be happy to share my experience with it should you need.

Hope I won't have to bother you more on this!
Nikolas

**Comment by kernel52** [comment]
as you have suggested. a simple include of a file containing the class declaration on the functions.php  and it worked. 
I've seen the namespace mismatch, I think I have tried both, but thanks for the help. 

I can move on with templating now :)
